### ISSUE TITLE
[Feature Request] Display in layout

### ISSUE THREAD

**Issue by ArchBlood** [humhub-contrib/auth-google#2]
To help clear up some issues that I personally dislike about the current workings, I believe creating a default layout within the `ACP > Settings` or in `ACP > Settings > Advanced` called "OAuth Clients" where custom OAuth modules would be able to create a tab container in this layout for their own OAuth module's configurations

**Comment by luke-** [comment]
![image](https://user-images.githubusercontent.com/4736168/96852267-38a64e00-1459-11eb-8a99-5d7440808012.png)

I personally think it's actually quite good if the settings for this are directly in the module. Especially since they normally have to be set only once.

But in the future we will improve the view of the modules and make the settings page more prominent.

Could this solves your problem?

**Comment by ArchBlood** [comment]
> ![image](https://user-images.githubusercontent.com/4736168/96852267-38a64e00-1459-11eb-8a99-5d7440808012.png)
> 
> I personally think it's actually quite good if the settings for this are directly in the module. Especially since they normally have to be set only once.
> 
> But in the future we will improve the view of the modules and make the settings page more prominent.
> 
> Could this solves your problem?

This could also be a solution to the problem at hand that
